name: pickaxe-env
channels:
 - rdkit
 - conda-forge
dependencies:
 - jupyter
 - mordred
 - numpy
 - numpydoc
 - pandas
 - pymongo
 - python>=3.9
 - rdkit
 - scikit-learn
 - scipy
 - sphinxcontrib-napoleon
 - sqlalchemy