[build-system]
requires = ["setuptools>=24.2.0","wheel"]
build-backend = "setuptools.build_meta"

[[tool.mypy.overrides]]
module = [
    "rdkit.*",
    "PIL.*",
    "IPython.*"
]
ignore_missing_imports = true

[tool.ruff]
line-length = 80

[tool.ruff.format]
line-ending = "lf"
