[build-system]
requires = ["setuptools>=24.2.0","wheel"]
build-backend = "setuptools.build_meta"

[[tool.mypy.overrides]]
module = "rdkit.*"
ignore_missing_imports = true

[tool.black]
line-length = 80

[tool.isort]
profile = "black"
line_length = 80

[tool.pylint.format]
max-line-length = "80"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py
isolated_build = true

[testenv]
deps =
    black
    isort
    jupyter-black
    mypy
commands =
    black --check .
    isort --check .
    mypy .
"""