name: test
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id}}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [macos, ubuntu, windows]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          cache: "pip"
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip list
      - name: Lint with Ruff and mypy
        run: |
          pip install .[lint]
          ruff check --output-format=github .
          ruff format --check --output-format=github .
          mypy --strict .
        continue-on-error: true
      - name: Test doranet with pytest
        run: |
          pip install .[test]
          pytest
